#!/usr/bin/env python3

from crazyflie_py import Crazyswarm
import time

TAKEOFF_DURATION = 2.5
HOVER_DURATION = 5.0
goal_pos = [0.0, 0.5, 0.5]

def main():
    '''
    swarm = Crazyswarm()
    timeHelper = swarm.timeHelper
    cf = swarm.allcfs.crazyflies[0]

    cf.takeoff(targetHeight=0.5, duration=TAKEOFF_DURATION)
    timeHelper.sleep(TAKEOFF_DURATION + HOVER_DURATION)

    cf.goTo(goal=goal_pos, yaw=0, duration=2.0)    
    timeHelper.sleep(2.0 + HOVER_DURATION)

    cf.land(targetHeight=0.04, duration=2.5)
    timeHelper.sleep(TAKEOFF_DURATION)
    '''

if __name__ == '__main__':
    main()
